//Order by Most traded currencies: https://en.wikipedia.org/wiki/Template:Most_traded_currencies
List<Map<String, dynamic>> currencies = [
  {
    "code": "USD",
    "name": "United States Dollar",
    "symbol": "\$",
    "flag": "USD",
    "alpha_2_code": "us",
    "decimal_digits": 2,
    "number": 840,
    "name_plural": "US dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "EUR",
    "name": "Euro",
    "symbol": "€",
    "flag": "EUR",
    "alpha_2_code": "eu",
    "decimal_digits": 2,
    "number": 978,
    "name_plural": "Euros",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "JPY",
    "name": "Japanese Yen",
    "symbol": "¥",
    "flag": "JPY",
    "alpha_2_code": "jp",
    "decimal_digits": 0,
    "number": 392,
    "name_plural": "Japanese yen",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "GBP",
    "name": "British Pound",
    "symbol": "£",
    "flag": "GBP",
    "alpha_2_code": "gb",
    "decimal_digits": 2,
    "number": 826,
    "name_plural": "British pounds sterling",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "AUD",
    "name": "Australian Dollar",
    "symbol": "\$",
    "flag": "AUD",
    "alpha_2_code": "au",
    "decimal_digits": 2,
    "number": 36,
    "name_plural": "Australian dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "CAD",
    "name": "Canadian Dollar",
    "symbol": "\$",
    "flag": "CAD",
    "alpha_2_code": "ca",
    "decimal_digits": 2,
    "number": 124,
    "name_plural": "Canadian dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "CHF",
    "name": "Switzerland Franc",
    "symbol": "CHF",
    "flag": "CHF",
    "alpha_2_code": "ch",
    "decimal_digits": 2,
    "number": 756,
    "name_plural": "Swiss francs",
    "thousands_separator": "'",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "CNY",
    "name": "China Yuan Renminbi",
    "symbol": "¥",
    "flag": "CNY",
    "alpha_2_code": "cn",
    "decimal_digits": 2,
    "number": 156,
    "name_plural": "Chinese yuan",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "HKD",
    "name": "Hong Kong Dollar",
    "symbol": "\$",
    "flag": "HKD",
    "alpha_2_code": "hk",
    "decimal_digits": 2,
    "number": 344,
    "name_plural": "Hong Kong dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "NZD",
    "name": "New Zealand Dollar",
    "symbol": "\$",
    "flag": "NZD",
    "alpha_2_code": "nz",
    "decimal_digits": 2,
    "number": 554,
    "name_plural": "New Zealand dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "SEK",
    "name": "Sweden Krona",
    "symbol": "kr",
    "flag": "SEK",
    "alpha_2_code": "se",
    "decimal_digits": 2,
    "number": 752,
    "name_plural": "Swedish kronor",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "KRW",
    "name": "South Korea Won",
    "symbol": "₩",
    "flag": "KRW",
    "alpha_2_code": "kr",
    "decimal_digits": 0,
    "number": 410,
    "name_plural": "South Korean won",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "SGD",
    "name": "Singapore Dollar",
    "symbol": "\$",
    "flag": "SGD",
    "alpha_2_code": "sg",
    "decimal_digits": 2,
    "number": 702,
    "name_plural": "Singapore dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "NOK",
    "name": "Norway Krone",
    "symbol": "kr",
    "flag": "NOK",
    "alpha_2_code": "no",
    "decimal_digits": 2,
    "number": 578,
    "name_plural": "Norwegian kroner",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "MXN",
    "name": "Mexico Peso",
    "symbol": "\$",
    "flag": "MXN",
    "alpha_2_code": "mx",
    "decimal_digits": 2,
    "number": 484,
    "name_plural": "Mexican pesos",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "INR",
    "name": "Indian Rupee",
    "symbol": "₹",
    "flag": "INR",
    "alpha_2_code": "in",
    "decimal_digits": 2,
    "number": 356,
    "name_plural": "Indian rupees",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "RUB",
    "name": "Russia Ruble",
    "symbol": "₽",
    "flag": "RUB",
    "alpha_2_code": "ru",
    "decimal_digits": 2,
    "number": 643,
    "name_plural": "Russian rubles",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "ZAR",
    "name": "South Africa Rand",
    "symbol": "R",
    "flag": "ZAR",
    "alpha_2_code": "za",
    "decimal_digits": 2,
    "number": 710,
    "name_plural": "South African rand",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "TRY",
    "name": "Turkish Lira",
    "symbol": "₺",
    "flag": "TRY",
    "alpha_2_code": "tr",
    "decimal_digits": 2,
    "number": 949,
    "name_plural": "Turkish Lira",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "BRL",
    "name": "Brazilian Real",
    "symbol": "R\$",
    "flag": "BRL",
    "alpha_2_code": "br",
    "decimal_digits": 2,
    "number": 986,
    "name_plural": "Brazilian Reais",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "TWD",
    "name": "Taiwan New Dollar",
    "symbol": "NT\$",
    "flag": "TWD",
    "alpha_2_code": "tw",
    "decimal_digits": 2,
    "number": 901,
    "name_plural": "New Taiwan dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "DKK",
    "name": "Denmark Krone",
    "symbol": "kr",
    "flag": "DKK",
    "alpha_2_code": "dk",
    "decimal_digits": 2,
    "number": 208,
    "name_plural": "Danish kroner",
    "thousands_separator": "",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "PLN",
    "name": "Poland Zloty",
    "symbol": "zł",
    "flag": "PLN",
    "alpha_2_code": "pl",
    "decimal_digits": 2,
    "number": 985,
    "name_plural": "Polish zlotys",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "THB",
    "name": "Thailand Baht",
    "symbol": "฿",
    "flag": "THB",
    "alpha_2_code": "th",
    "decimal_digits": 2,
    "number": 764,
    "name_plural": "Thai baht",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "IDR",
    "name": "Indonesia Rupiah",
    "symbol": "Rp",
    "flag": "IDR",
    "alpha_2_code": "id",
    "decimal_digits": 0,
    "number": 360,
    "name_plural": "Indonesian rupiahs",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "HUF",
    "name": "Hungary Forint",
    "symbol": "Ft",
    "flag": "HUF",
    "alpha_2_code": "hu",
    "decimal_digits": 0,
    "number": 348,
    "name_plural": "Hungarian forints",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "CZK",
    "name": "Czech Koruna",
    "symbol": "Kč",
    "flag": "CZK",
    "alpha_2_code": "cz",
    "decimal_digits": 2,
    "number": 203,
    "name_plural": "Czech Republic korunas",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "ILS",
    "name": "Israel Shekel",
    "symbol": "₪",
    "flag": "ILS",
    "alpha_2_code": "il",
    "decimal_digits": 2,
    "number": 376,
    "name_plural": "Israeli new sheqels",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "CLP",
    "name": "Chile Peso",
    "symbol": "\$",
    "flag": "CLP",
    "alpha_2_code": "cl",
    "decimal_digits": 0,
    "number": 152,
    "name_plural": "Chilean pesos",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "PHP",
    "name": "Philippines Peso",
    "symbol": "₱",
    "flag": "PHP",
    "alpha_2_code": "ph",
    "decimal_digits": 2,
    "number": 608,
    "name_plural": "Philippine pesos",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "AED",
    "name": "Emirati Dirham",
    "symbol": "د.إ",
    "flag": "AED",
    "alpha_2_code": "ae",
    "decimal_digits": 2,
    "number": 784,
    "name_plural": "UAE dirhams",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "COP",
    "name": "Colombia Peso",
    "symbol": "\$",
    "flag": "COP",
    "alpha_2_code": "co",
    "decimal_digits": 0,
    "number": 170,
    "name_plural": "Colombian pesos",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "SAR",
    "name": "Saudi Arabia Riyal",
    "symbol": "﷼",
    "flag": "SAR",
    "alpha_2_code": "sa",
    "decimal_digits": 2,
    "number": 682,
    "name_plural": "Saudi riyals",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "MYR",
    "name": "Malaysia Ringgit",
    "symbol": "RM",
    "flag": "MYR",
    "alpha_2_code": "my",
    "decimal_digits": 2,
    "number": 458,
    "name_plural": "Malaysian ringgits",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "RON",
    "name": "Romania Leu",
    "symbol": "L",
    "flag": "RON",
    "alpha_2_code": "ro",
    "decimal_digits": 2,
    "number": 946,
    "name_plural": "Romanian lei",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "AFN",
    "name": "Afghanistan Afghani",
    "symbol": "؋",
    "flag": "AFN",
    "alpha_2_code": "af",
    "decimal_digits": 0,
    "number": 971,
    "name_plural": "Afghan Afghanis",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "ALL",
    "name": "Albanian Lek",
    "symbol": "Lek",
    "flag": "ALB",
    "alpha_2_code": "al",
    "decimal_digits": 0,
    "number": 8,
    "name_plural": "Albanian lekë",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "DZD",
    "name": "Algerian dinar",
    "symbol": "دج",
    "flag": "DZ",
    "alpha_2_code": "dz",
    "decimal_digits": 2,
    "number": 012,
    "name_plural": "Algerian dinars",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "AOA",
    "name": "Angolan Kwanza",
    "symbol": "Kz",
    "flag": "AO",
    "alpha_2_code": "ao",
    "decimal_digits": 2,
    "number": 973,
    "name_plural": "Angolan kwanzas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "ARS",
    "name": "Argentine Peso",
    "symbol": "\$",
    "flag": "ARS",
    "alpha_2_code": "ar",
    "decimal_digits": 2,
    "number": 32,
    "name_plural": "Argentine pesos",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "AMD",
    "name": "Armenian Dram",
    "symbol": "֏",
    "flag": "AM",
    "alpha_2_code": "am",
    "decimal_digits": 0,
    "number": 51,
    "name_plural": "Armenian drams",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "AZN",
    "name": "Azerbaijani Manat",
    "symbol": "₼",
    "flag": "AZE",
    "alpha_2_code": "az",
    "decimal_digits": 2,
    "number": 100,
    "name_plural": "Azerbaijani manats",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "BHD",
    "name": "Bahraini Dinar",
    "symbol": "BD",
    "flag": "BHD",
    "alpha_2_code": "bh",
    "decimal_digits": 3,
    "number": 48,
    "name_plural": "Bahraini dinars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "BDT",
    "name": "Bangladeshi Taka",
    "symbol": "৳",
    "flag": "BDT",
    "alpha_2_code": "bd",
    "decimal_digits": 2,
    "number": 50,
    "name_plural": "Bangladeshi takas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "BBD",
    "name": "Barbados Dollar",
    "symbol": "\$",
    "flag": "BBD",
    "alpha_2_code": "bb",
    "decimal_digits": 2,
    "number": 52,
    "name_plural": "Barbados dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "BYN",
    "name": "Belarussian Ruble",
    "symbol": "Br",
    "flag": "BY",
    "alpha_2_code": "by",
    "decimal_digits": 2,
    "number": 933,
    "name_plural": "Belarusian rubles",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "BZD",
    "name": "Belize Dollar",
    "symbol": "BZ\$",
    "flag": "BZD",
    "alpha_2_code": "bz",
    "decimal_digits": 2,
    "number": 84,
    "name_plural": "Belize dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "BMD",
    "name": "Bermuda Dollar",
    "symbol": "\$",
    "flag": "BMD",
    "alpha_2_code": "bm",
    "decimal_digits": 2,
    "number": 60,
    "name_plural": "Bermuda dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "BTN",
    "name": "Bhutanese Ngultrum",
    "symbol": "Nu.",
    "flag": "BTN",
    "alpha_2_code": "bt",
    "decimal_digits": 2,
    "number": 64,
    "name_plural": "Bhutanese ngultrums",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "BOB",
    "name": "Bolivia Bolíviano",
    "symbol": "\$b",
    "flag": "BOB",
    "alpha_2_code": "bo",
    "decimal_digits": 2,
    "number": 68,
    "name_plural": "Bolivian bolivianos",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "BAM",
    "name": "Bosnia and Herzegovina convertible mark",
    "symbol": "KM",
    "flag": "BA",
    "alpha_2_code": "ba",
    "decimal_digits": 2,
    "number": 977,
    "name_plural": "Bosnia and Herzegovina convertible marks",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "BWP",
    "name": "Botswanan Pula",
    "symbol": "P",
    "flag": "BW",
    "alpha_2_code": "bw",
    "decimal_digits": 2,
    "number": 72,
    "name_plural": "Botswanan pulas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "BND",
    "name": "Brunei Darussalam Dollar",
    "symbol": "\$",
    "flag": "BND",
    "alpha_2_code": "bn",
    "decimal_digits": 2,
    "number": 96,
    "name_plural": "Brunei dollars",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "BGN",
    "name": "Bulgarian Lev",
    "symbol": "лв",
    "flag": "BGN",
    "alpha_2_code": "bg",
    "decimal_digits": 2,
    "number": 975,
    "name_plural": "Bulgarian leva",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "BIF",
    "name": "Burundian Franc",
    "symbol": "FBu",
    "flag": "BI",
    "alpha_2_code": "bi",
    "decimal_digits": 2,
    "number": 108,
    "name_plural": "Burundian Franc",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "KHR",
    "name": "Cambodian riel",
    "symbol": "៛",
    "flag": "KHM",
    "alpha_2_code": "kh",
    "decimal_digits": 2,
    "number": 116,
    "name_plural": "Cambodian riels",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "KYD",
    "name": "Cayman Islands Dollar",
    "symbol": "\$",
    "flag": "KYD",
    "alpha_2_code": "ky",
    "decimal_digits": 2,
    "number": 136,
    "name_plural": "Cayman islands dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "XAF",
    "name": "Central African CFA franc",
    "symbol": "FCFA",
    "flag": null,
    "alpha_2_code": "cf",
    "decimal_digits": 2,
    "number": 950,
    "name_plural": "Central African CFA francs",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "XOF",
    "name": "UEMOA CFA franc",
    "symbol": "FCFA",
    "flag": "xof.png",
    "alpha_2_code": "wf",
    "decimal_digits": 2,
    "number": 960,
    "name_plural": "UEMOA CFA francs",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "CDF",
    "name": "Congolese franc",
    "symbol": "FC",
    "flag": "CD",
    "alpha_2_code": "cd",
    "decimal_digits": 2,
    "number": 976,
    "name_plural": "Congolese francs",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "CRC",
    "name": "Costa Rica Colon",
    "symbol": "₡",
    "flag": "CRC",
    "alpha_2_code": "cr",
    "decimal_digits": 0,
    "number": 188,
    "name_plural": "Costa Rican colóns",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "CUP",
    "name": "Cuban Peso",
    "symbol": "\$MN",
    "flag": "CU",
    "alpha_2_code": "cu",
    "decimal_digits": 2,
    "number": 192,
    "name_plural": "Cuban pesos",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "DOP",
    "name": "Dominican Republic Peso",
    "symbol": "RD\$",
    "flag": "DOP",
    "alpha_2_code": "do",
    "decimal_digits": 2,
    "number": 214,
    "name_plural": "Dominican pesos",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "EGP",
    "name": "Egypt Pound",
    "symbol": "£",
    "flag": "EGP",
    "alpha_2_code": "eg",
    "decimal_digits": 2,
    "number": 818,
    "name_plural": "Egyptian pounds",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "ETB",
    "name": "Ethiopian Birr",
    "symbol": "Br",
    "flag": "ETB",
    "alpha_2_code": "et",
    "decimal_digits": 2,
    "number": 230,
    "name_plural": "Ethiopian birrs",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "GMD",
    "name": "Gambian dalasi",
    "symbol": "D",
    "flag": "GMD",
    "alpha_2_code": "gm",
    "decimal_digits": 2,
    "number": 270,
    "name_plural": "Gambian dalasis",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "GEL",
    "name": "Georgian Lari",
    "symbol": "₾",
    "flag": "GEL",
    "alpha_2_code": "ge",
    "decimal_digits": 2,
    "number": 981,
    "name_plural": "Georgian laris",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "GHS",
    "name": "Ghana Cedi",
    "symbol": "₵",
    "flag": "GHS",
    "alpha_2_code": "gh",
    "decimal_digits": 2,
    "number": 936,
    "name_plural": "Ghanaian cedis",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "GTQ",
    "name": "Guatemalan quetzal",
    "symbol": "Q",
    "flag": "GT",
    "alpha_2_code": "gt",
    "decimal_digits": 2,
    "number": 320,
    "name_plural": "Guatemalan quetzales",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "GYD",
    "name": "Guyana Dollar",
    "symbol": "\$",
    "flag": "GYD",
    "alpha_2_code": "gy",
    "decimal_digits": 2,
    "number": 328,
    "name_plural": "Guyana dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "HTG",
    "name": "Haitian gourde",
    "symbol": "G",
    "flag": "HTI",
    "alpha_2_code": "ht",
    "decimal_digits": 2,
    "number": 332,
    "name_plural": "Haitian gourdes",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "ISK",
    "name": "Iceland Krona",
    "symbol": "kr",
    "flag": "ISK",
    "alpha_2_code": "is",
    "decimal_digits": 0,
    "number": 352,
    "name_plural": "Icelandic krónur",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "IQD",
    "name": "Iraqi Dinar",
    "symbol": "د.ع",
    "flag": "IQD",
    "alpha_2_code": "iq",
    "decimal_digits": 3,
    "number": 368,
    "name_plural": "Iraqi dinars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "JMD",
    "name": "Jamaica Dollar",
    "symbol": "J\$",
    "flag": "JMD",
    "alpha_2_code": "jm",
    "decimal_digits": 2,
    "number": 388,
    "name_plural": "Jamaican dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "JOD",
    "name": "Jordanian dinar",
    "symbol": "د.أ",
    "flag": "JO",
    "alpha_2_code": "jo",
    "decimal_digits": 3,
    "number": 400,
    "name_plural": "Jordanian dinars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "KZT",
    "name": "Kazakhstan Tenge",
    "symbol": "〒",
    "flag": "KZT",
    "alpha_2_code": "kz",
    "decimal_digits": 2,
    "number": 398,
    "name_plural": "Kazakhstani tenges",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "KES",
    "name": "Kenyan Shilling",
    "symbol": "KSh",
    "flag": "KES",
    "alpha_2_code": "ke",
    "decimal_digits": 2,
    "number": 404,
    "name_plural": "Kenyan shillings",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "KWD",
    "name": "Kuwaiti Dinar",
    "symbol": "د.ك",
    "flag": "KWD",
    "alpha_2_code": "kw",
    "decimal_digits": 3,
    "number": 414,
    "name_plural": "Kuwaiti dinars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "KGS",
    "name": "Kyrgyzstani som",
    "symbol": "с",
    "flag": "KG",
    "alpha_2_code": "kg",
    "decimal_digits": 2,
    "number": 417,
    "name_plural": "Kyrgyzstani som",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "LAK",
    "name": "Laos Kip",
    "symbol": "₭",
    "flag": "LAK",
    "alpha_2_code": "la",
    "decimal_digits": 2,
    "number": 418,
    "name_plural": "Laos Kip",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "LBP",
    "name": "Lebanese Pound",
    "symbol": "ل.ل",
    "flag": "LB",
    "alpha_2_code": "lb",
    "decimal_digits": 2,
    "number": 422,
    "name_plural": "Lebanese pounds",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "LRD",
    "name": "Liberia Dollar",
    "symbol": "\$",
    "flag": "LRD",
    "alpha_2_code": "lr",
    "decimal_digits": 2,
    "number": 430,
    "name_plural": "Liberia dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "MKD",
    "name": "Macedonia Denar",
    "symbol": "ден",
    "flag": "MKD",
    "alpha_2_code": "mk",
    "decimal_digits": 2,
    "number": 807,
    "name_plural": "Macedonian denari",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "MGA",
    "name": "Malagasy Ariary",
    "symbol": "Ar",
    "flag": "MG",
    "alpha_2_code": "mg",
    "decimal_digits": 0,
    "number": 969,
    "name_plural": "Malagasy ariaries",
    "thousands_separator": " ",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "MWK",
    "name": "Malawian Kwacha",
    "symbol": "MK",
    "flag": "MWK",
    "alpha_2_code": "mw",
    "decimal_digits": 2,
    "number": 454,
    "name_plural": "Malawian kwachas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "MVR",
    "name": "Maldivian Rufiyaa",
    "symbol": "/-",
    "flag": "MV",
    "alpha_2_code": "mv",
    "decimal_digits": 2,
    "number": 462,
    "name_plural": "Maldivian Rufiyaa",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "MUR",
    "name": "Mauritius Rupee",
    "symbol": "₨",
    "flag": "MUR",
    "alpha_2_code": "mu",
    "decimal_digits": 0,
    "number": 480,
    "name_plural": "Mauritian rupees",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "MDL",
    "name": "Moldovan Leu",
    "symbol": "L",
    "flag": "MDL",
    "alpha_2_code": "md",
    "decimal_digits": 2,
    "number": 498,
    "name_plural": "Moldovan lei",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "MNT",
    "name": "Mongolia Tughrik",
    "symbol": "₮",
    "flag": "MNT",
    "alpha_2_code": "mn",
    "decimal_digits": 2,
    "number": 496,
    "name_plural": "Mongolia tugriks",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "MAD",
    "name": "Moroccan Dirham",
    "symbol": "MAD",
    "flag": "MAD",
    "alpha_2_code": "ma",
    "decimal_digits": 2,
    "number": 504,
    "name_plural": "Moroccan dirhams",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "MZN",
    "name": "Mozambique Metical",
    "symbol": "MT",
    "flag": "MZN",
    "alpha_2_code": "mz",
    "decimal_digits": 2,
    "number": 943,
    "name_plural": "Mozambican meticals",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "MMK",
    "name": "Myanmar Kyat",
    "symbol": "Ks",
    "flag": "MM",
    "alpha_2_code": "mm",
    "decimal_digits": 2,
    "number": 104,
    "name_plural": "Myanmar Kyats",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "NAD",
    "name": "Namibia Dollar",
    "symbol": "\$",
    "flag": "NAD",
    "alpha_2_code": "na",
    "decimal_digits": 2,
    "number": 516,
    "name_plural": "Namibian dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "NPR",
    "name": "Nepal Rupee",
    "symbol": "₨",
    "flag": "NPR",
    "alpha_2_code": "np",
    "decimal_digits": 2,
    "number": 524,
    "name_plural": "Nepalese rupees",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "NIO",
    "name": "Nicaragua Cordoba",
    "symbol": "C\$",
    "flag": "NIO",
    "alpha_2_code": "ni",
    "decimal_digits": 2,
    "number": 558,
    "name_plural": "Nicaraguan córdobas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "NGN",
    "name": "Nigeria Naira",
    "symbol": "₦",
    "flag": "NGN",
    "alpha_2_code": "ng",
    "decimal_digits": 2,
    "number": 566,
    "name_plural": "Nigerian nairas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "OMR",
    "name": "Oman Rial",
    "symbol": "﷼",
    "flag": "OMR",
    "alpha_2_code": "om",
    "decimal_digits": 3,
    "number": 512,
    "name_plural": "Omani rials",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "PKR",
    "name": "Pakistan Rupee",
    "symbol": "₨",
    "flag": "PKR",
    "alpha_2_code": "pk",
    "decimal_digits": 0,
    "number": 586,
    "name_plural": "Pakistani rupees",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "PGK",
    "name": "Papua New Guinean Kina",
    "symbol": "K",
    "flag": "PGK",
    "alpha_2_code": "pg",
    "decimal_digits": 2,
    "number": 598,
    "name_plural": "Papua New Guinean Kina",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "PYG",
    "name": "Paraguay Guarani",
    "symbol": "₲",
    "flag": "PYG",
    "alpha_2_code": "py",
    "decimal_digits": 0,
    "number": 600,
    "name_plural": "Paraguayan guaranis",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "PEN",
    "name": "Peru Sol",
    "symbol": "S/.",
    "flag": "PEN",
    "alpha_2_code": "pe",
    "decimal_digits": 2,
    "number": 604,
    "name_plural": "Peruvian nuevos soles",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "QAR",
    "name": "Qatar Riyal",
    "symbol": "﷼",
    "flag": "QAR",
    "alpha_2_code": "qa",
    "decimal_digits": 2,
    "number": 634,
    "name_plural": "Qatari rials",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "RWF",
    "name": "Rwandan franc",
    "symbol": "FRw",
    "flag": "RWA",
    "alpha_2_code": "rw",
    "decimal_digits": 0,
    "number": 646,
    "name_plural": "Rwandan francs",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "RSD",
    "name": "Serbia Dinar",
    "symbol": "Дин.",
    "flag": "RSD",
    "alpha_2_code": "rs",
    "decimal_digits": 0,
    "number": 941,
    "name_plural": "Serbian dinars",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "SCR",
    "name": "Seychellois rupee",
    "symbol": "₨",
    "flag": "SC",
    "alpha_2_code": "sc",
    "decimal_digits": 2,
    "number": 690,
    "name_plural": "Seychelles rupee",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "SOS",
    "name": "Somalia Shilling",
    "symbol": "S",
    "flag": "SOS",
    "alpha_2_code": "so",
    "decimal_digits": 0,
    "number": 706,
    "name_plural": "Somali shillings",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "LKR",
    "name": "Sri Lanka Rupee",
    "symbol": "₨",
    "flag": "LKR",
    "alpha_2_code": "lk",
    "decimal_digits": 2,
    "number": 144,
    "name_plural": "Sri Lankan rupees",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "SRD",
    "name": "Suriname Dollar",
    "symbol": "\$",
    "flag": "SRD",
    "alpha_2_code": "sr",
    "decimal_digits": 2,
    "number": 968,
    "name_plural": "Suriname Dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "SYP",
    "name": "Syrian Lira",
    "symbol": "LS",
    "flag": "SYP",
    "alpha_2_code": "sy",
    "decimal_digits": 2,
    "number": 760,
    "name_plural": "Syrian lira",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "TZS",
    "name": "Tanzanian Shilling",
    "symbol": "TSh",
    "flag": "TZS",
    "alpha_2_code": "tz",
    "decimal_digits": 0,
    "number": 834,
    "name_plural": "Tanzanian shillings",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "TOP",
    "name": "Tongan Pa'anga",
    "symbol": "T\$",
    "flag": "TO",
    "alpha_2_code": "to",
    "decimal_digits": 2,
    "number": 776,
    "name_plural": "Tongan pa'angas",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "TTD",
    "name": "Trinidad and Tobago Dollar",
    "symbol": "TT\$",
    "flag": "TTD",
    "alpha_2_code": "tt",
    "decimal_digits": 2,
    "number": 780,
    "name_plural": "Trinidad and Tobago dollars",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "TND",
    "name": "Tunisian dinar",
    "symbol": "د.ت",
    "flag": "TN",
    "alpha_2_code": "tn",
    "decimal_digits": 3,
    "number": 788,
    "name_plural": "Tunisian dinars",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "UGX",
    "name": "Ugandan Shilling",
    "symbol": "USh",
    "flag": "UGX",
    "alpha_2_code": "ug",
    "decimal_digits": 0,
    "number": 800,
    "name_plural": "Ugandan shillings",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "UAH",
    "name": "Ukraine Hryvnia",
    "symbol": "₴",
    "flag": "UAH",
    "alpha_2_code": "ua",
    "decimal_digits": 2,
    "number": 980,
    "name_plural": "Ukrainian hryvnias",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": false,
  },
  {
    "code": "UYU",
    "name": "Uruguay Peso",
    "symbol": "\$U",
    "flag": "UYU",
    "alpha_2_code": "uy",
    "decimal_digits": 2,
    "number": 858,
    "name_plural": "Uruguayan pesos",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "VEF",
    "name": "Venezuela Bolívar",
    "symbol": "Bs",
    "flag": "VEF",
    "alpha_2_code": "ve",
    "decimal_digits": 2,
    "number": 937,
    "name_plural": "Venezuelan bolívars",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "VND",
    "name": "Vietnamese Dong",
    "symbol": "₫",
    "flag": "VND",
    "alpha_2_code": "vn",
    "decimal_digits": 0,
    "number": 704,
    "name_plural": "Vietnamese dong",
    "thousands_separator": ".",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": false,
  },
  {
    "code": "YER",
    "name": "Yemen Rial",
    "symbol": "﷼",
    "flag": "YER",
    "alpha_2_code": "ye",
    "decimal_digits": 2,
    "number": 886,
    "name_plural": "Yemeni rials",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
  },
  {
    "code": "ZMW",
    "name": "Zambian kwacha",
    "symbol": "ZK",
    "flag": "ZM",
    "alpha_2_code": "zm",
    "decimal_digits": 2,
    "number": 967,
    "name_plural": "Zambian kwachas",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
  {
    "code": "ZWL",
    "name": "Zimbabwean Dollar",
    "symbol": "\$ZWL",
    "flag": "ZW",
    "alpha_2_code": "zw",
    "decimal_digits": 2,
    "number": 932,
    "name_plural": "Zimbabwean dollars",
    "thousands_separator": " ",
    "decimal_separator": ",",
    "space_between_amount_and_symbol": false,
    "symbol_on_left": true,
  },
];
